export const APP_NAME = 'MOB';
export const APP_TAGLINE = 'Retail POS & Inventory';
export const APP_FULL_NAME = 'MOB - Retail POS & Inventory';
export const APP_MEANING = 'Mobile Operated Business';
export const INVOICE_BRANDING = 'Generated by MOB';
