export const APP_NAME = 'MOPX';
export const APP_TAGLINE = 'Retail POS & Inventory';
export const APP_FULL_NAME = 'MOPX - Retail POS & Inventory';
export const APP_MEANING = 'Mobile Operated POS, extended';
export const INVOICE_BRANDING = 'Generated by MOPX';
